# Generated by Django 6.0.4 on 2026-04-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='advance_payment_amount',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Fixed advance payment required to book', max_digits=10),
        ),
    ]
