# Generated by Django 6.0.4 on 2026-05-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(choices=[('NIGHTLY', 'Nightly'), ('DAILY', 'Daily'), ('MONTHLY', 'Monthly')], default='NIGHTLY', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='allows_daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='allows_monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='allows_nightly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
